services:
  - type: web
    name: my-go-app
    env: go
    plan: free  # 使用免费计划
    buildCommand: "echo 'No build step needed.'"  # 因为我们已经打包好了，不需要构建
    startCommand: "chmod +x ./channel && ./channel"  # 运行二进制文件
    autoDeploy: true  # 启用自动部署
    branch: main  # 部署的 Git 分支
    region: oregon  # 选择部署的区域
    healthCheckPath: "/"  # 健康检查的路径
    envVars:  # 如果你有需要的环境变量可以在这里定义
      - key: PORT
        value: 8080  # 确保使用 Render 提供的端口
